var paasrest_dns="https://mis.dayang.com/mis-rest";
tenantSelfinterfaces={
		//创建订单he维护订单租户和组织机构的关系
		Var_createPaasOrder:'http://localhost:8080/passService/createPaasOrder',
		//查询已购买的应用（订单，模板，实例）
		Var_showApplicationList:'http://localhost:8080/passService/showApplicationList',
		//查询应用详情(实例详情)
		Var_showApplicationDetails:'http://localhost:8080/passService/showApplicationDetails',
		//获取应用实例和组织机构的关系
		Var_getInstanceAndOrgShip:'http://localhost:8080/passService/getInstanceAndOrgShip',
		//插入订单组织机构关系
		Var_addInstanceAndOrgShip:'http://localhost:8080/passService/addInstanceAndOrgShip',
		//删除订单组织机构关系
		Var_deleteInstanceAndOrgShip:'http://localhost:8080/passService/deleteInstanceAndOrgShip',
		//查询已发布的产品列表（订单，模板，实例）
		Var_showTempliteList:'http://localhost:8080/passService/showTempliteList',
		//获取模板分类
		Var_getTemplateCategorys:'http://localhost:8080/passService/getTemplateCategorys',
};