package rest.mybatis.dao.passDao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import rest.mybatis.model.passModel.PaasTemplate;

public interface PaasTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insert(PaasTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insertSelective(PaasTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    PaasTemplate selectByPrimaryKey(Integer id);
    //条件查询产品列表
    List<PaasTemplate> selectpaasTemplateList(@Param("page")Integer page,
    		@Param("id")Integer id,
    		@Param("templateId") String templateId,
    		@Param("templateCategory") String templateCategory,
    		@Param("counm") Integer counm);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(PaasTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PaasTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKey(PaasTemplate record);
}