package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PaasInstance;

public interface PaasInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int deleteByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insert(PaasInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insertSelective(PaasInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    PaasInstance selectByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(PaasInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_INSTANCE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKey(PaasInstance record);
}