package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PaasTemplateFile;

public interface PaasTemplateFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insert(PaasTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insertSelective(PaasTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    PaasTemplateFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(PaasTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PaasTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_TEMPLATE_FILE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKey(PaasTemplateFile record);
}