package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PaasOrder;

public interface PaasOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insert(PaasOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insertSelective(PaasOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    PaasOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(PaasOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORDER
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKey(PaasOrder record);
}