package rest.mybatis.dao.passDao;

import java.util.List;

import rest.mybatis.model.passModel.PaasSubservice;

public interface PaasSubserviceMapper {
	
	List<PaasSubservice> selectSubServiceByTPlId(String templateId);
	List<PaasSubservice> selectSubServiceBytemplateId(Integer templateId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    int insert(PaasSubservice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    int insertSelective(PaasSubservice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    PaasSubservice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    int updateByPrimaryKeySelective(PaasSubservice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_SUBSERVICE
     *
     * @mbggenerated Wed May 10 16:21:06 CST 2017
     */
    int updateByPrimaryKey(PaasSubservice record);
}