package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PaasOrdTenantOrgR;

public interface PaasOrdTenantOrgRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insert(PaasOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int insertSelective(PaasOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    PaasOrdTenantOrgR selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKeySelective(PaasOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    int updateByPrimaryKey(PaasOrdTenantOrgR record);
}