package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PaasUserSubOrg;

public interface PaasUserSubOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int insert(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int insertSelective(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    PaasUserSubOrg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int updateByPrimaryKeySelective(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int updateByPrimaryKey(PaasUserSubOrg record);
}