package rest.mybatis.dao.passDao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import rest.mybatis.model.passModel.PaasUserSubOrg;

public interface PaasUserSubOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByBiilNumAndMoldeId(@Param("billNum")String billNum,@Param("modelId")String modelId);
    int deleteByBillNum(String billNum);
    int deleteByBillNumMoeIdUserId(@Param("billNum")String billNum,@Param("modelId")String modelId,
    		@Param("userId")String userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int insert(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int insertSelective(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    PaasUserSubOrg selectByPrimaryKey(Integer id);
    List<PaasUserSubOrg> selectByBillno(String billno);
    List<PaasUserSubOrg> selectByBillnoandType(String billno);
    List<PaasUserSubOrg> selectModelsByuserOrOrdIds(List<String> userOrOrdIds);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int updateByPrimaryKeySelective(PaasUserSubOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAAS_USER_SUB_ORG
     *
     * @mbggenerated Fri Jun 16 13:48:44 CST 2017
     */
    int updateByPrimaryKey(PaasUserSubOrg record);
    
    List<PaasUserSubOrg> getPaasUserSubOrg(Map<String,String> map);
}