package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassInstance;

public interface PassInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    int deleteByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    int insert(PassInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    int insertSelective(PassInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    PassInstance selectByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    int updateByPrimaryKeySelective(PassInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_INSTANCE
     *
     * @mbggenerated Mon May 08 13:48:44 CST 2017
     */
    int updateByPrimaryKey(PassInstance record);
}