package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassUser;

public interface PassUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int insert(PassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int insertSelective(PassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    PassUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int updateByPrimaryKeySelective(PassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserT
     *
     * @mbggenerated Thu Apr 27 10:11:45 CST 2017
     */
    int updateByPrimaryKey(PassUser record);
}