package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassTemplateFile;

public interface PassTemplateFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insert(PassTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insertSelective(PassTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    PassTemplateFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKeySelective(PassTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PassTemplateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_TEMPLATE_FILE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKey(PassTemplateFile record);
}