package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassModule;

public interface PassModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insert(PassModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insertSelective(PassModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    PassModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKeySelective(PassModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_MODULE
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKey(PassModule record);
}