package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassOrdTenantOrgR;

public interface PassOrdTenantOrgRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insert(PassOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int insertSelective(PassOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    PassOrdTenantOrgR selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKeySelective(PassOrdTenantOrgR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORD_TENANT_ORG_R
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    int updateByPrimaryKey(PassOrdTenantOrgR record);
}