package rest.mybatis.dao.passDao;

import rest.mybatis.model.passModel.PassOrder;

public interface PassOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    int insert(PassOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    int insertSelective(PassOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    PassOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    int updateByPrimaryKeySelective(PassOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PASS_ORDER
     *
     * @mbggenerated Mon May 08 14:22:27 CST 2017
     */
    int updateByPrimaryKey(PassOrder record);
}