package rest.mybatis.model.passModel;

public class PaasOrdTenantOrgR {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_ORD_TENANT_ORG_R.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_ORD_TENANT_ORG_R.ORD_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer ordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_ORD_TENANT_ORG_R.TENANT_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_ORD_TENANT_ORG_R.ORG_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_ORD_TENANT_ORG_R.ID
     *
     * @return the value of PAAS_ORD_TENANT_ORG_R.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_ORD_TENANT_ORG_R.ID
     *
     * @param id the value for PAAS_ORD_TENANT_ORG_R.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_ORD_TENANT_ORG_R.ORD_ID
     *
     * @return the value of PAAS_ORD_TENANT_ORG_R.ORD_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_ORD_TENANT_ORG_R.ORD_ID
     *
     * @param ordId the value for PAAS_ORD_TENANT_ORG_R.ORD_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setOrdId(Integer ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_ORD_TENANT_ORG_R.TENANT_ID
     *
     * @return the value of PAAS_ORD_TENANT_ORG_R.TENANT_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_ORD_TENANT_ORG_R.TENANT_ID
     *
     * @param tenantId the value for PAAS_ORD_TENANT_ORG_R.TENANT_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_ORD_TENANT_ORG_R.ORG_ID
     *
     * @return the value of PAAS_ORD_TENANT_ORG_R.ORG_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_ORD_TENANT_ORG_R.ORG_ID
     *
     * @param orgId the value for PAAS_ORD_TENANT_ORG_R.ORG_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}