package rest.mybatis.model.passModel;

public class PaasTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.TEMPLATE_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.VERSION
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.TEMPLATE_TYPE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.TEMPLATE_CATEGORY
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String templateCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.USER_MODE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String userMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.PRICE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.IS_PUB
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private Integer isPub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAAS_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    private String templateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.ID
     *
     * @return the value of PAAS_TEMPLATE.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.ID
     *
     * @param id the value for PAAS_TEMPLATE.ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.TEMPLATE_ID
     *
     * @return the value of PAAS_TEMPLATE.TEMPLATE_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.TEMPLATE_ID
     *
     * @param templateId the value for PAAS_TEMPLATE.TEMPLATE_ID
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.VERSION
     *
     * @return the value of PAAS_TEMPLATE.VERSION
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.VERSION
     *
     * @param version the value for PAAS_TEMPLATE.VERSION
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.TEMPLATE_TYPE
     *
     * @return the value of PAAS_TEMPLATE.TEMPLATE_TYPE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.TEMPLATE_TYPE
     *
     * @param templateType the value for PAAS_TEMPLATE.TEMPLATE_TYPE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType == null ? null : templateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.TEMPLATE_CATEGORY
     *
     * @return the value of PAAS_TEMPLATE.TEMPLATE_CATEGORY
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getTemplateCategory() {
        return templateCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.TEMPLATE_CATEGORY
     *
     * @param templateCategory the value for PAAS_TEMPLATE.TEMPLATE_CATEGORY
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setTemplateCategory(String templateCategory) {
        this.templateCategory = templateCategory == null ? null : templateCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.USER_MODE
     *
     * @return the value of PAAS_TEMPLATE.USER_MODE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getUserMode() {
        return userMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.USER_MODE
     *
     * @param userMode the value for PAAS_TEMPLATE.USER_MODE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setUserMode(String userMode) {
        this.userMode = userMode == null ? null : userMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.PRICE
     *
     * @return the value of PAAS_TEMPLATE.PRICE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.PRICE
     *
     * @param price the value for PAAS_TEMPLATE.PRICE
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.IS_PUB
     *
     * @return the value of PAAS_TEMPLATE.IS_PUB
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public Integer getIsPub() {
        return isPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.IS_PUB
     *
     * @param isPub the value for PAAS_TEMPLATE.IS_PUB
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setIsPub(Integer isPub) {
        this.isPub = isPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAAS_TEMPLATE.TEMPLATE_NAME
     *
     * @return the value of PAAS_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAAS_TEMPLATE.TEMPLATE_NAME
     *
     * @param templateName the value for PAAS_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated Mon May 08 16:50:01 CST 2017
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }
}