package rest.mybatis.model.passModel;

public class PassModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.TEMPLATE_ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.MODULE_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.MODULE_URL
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.MODULE_IS_DIS
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private String moduleIsDis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.MODULE_DES
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private String moduleDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PASS_MODULE.MODULE_IMG_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    private String moduleImgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.ID
     *
     * @return the value of PASS_MODULE.ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.ID
     *
     * @param id the value for PASS_MODULE.ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.TEMPLATE_ID
     *
     * @return the value of PASS_MODULE.TEMPLATE_ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.TEMPLATE_ID
     *
     * @param templateId the value for PASS_MODULE.TEMPLATE_ID
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.MODULE_NAME
     *
     * @return the value of PASS_MODULE.MODULE_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.MODULE_NAME
     *
     * @param moduleName the value for PASS_MODULE.MODULE_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.MODULE_URL
     *
     * @return the value of PASS_MODULE.MODULE_URL
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.MODULE_URL
     *
     * @param moduleUrl the value for PASS_MODULE.MODULE_URL
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.MODULE_IS_DIS
     *
     * @return the value of PASS_MODULE.MODULE_IS_DIS
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public String getModuleIsDis() {
        return moduleIsDis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.MODULE_IS_DIS
     *
     * @param moduleIsDis the value for PASS_MODULE.MODULE_IS_DIS
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setModuleIsDis(String moduleIsDis) {
        this.moduleIsDis = moduleIsDis == null ? null : moduleIsDis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.MODULE_DES
     *
     * @return the value of PASS_MODULE.MODULE_DES
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public String getModuleDes() {
        return moduleDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.MODULE_DES
     *
     * @param moduleDes the value for PASS_MODULE.MODULE_DES
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setModuleDes(String moduleDes) {
        this.moduleDes = moduleDes == null ? null : moduleDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASS_MODULE.MODULE_IMG_NAME
     *
     * @return the value of PASS_MODULE.MODULE_IMG_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public String getModuleImgName() {
        return moduleImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASS_MODULE.MODULE_IMG_NAME
     *
     * @param moduleImgName the value for PASS_MODULE.MODULE_IMG_NAME
     *
     * @mbggenerated Fri May 05 15:59:28 CST 2017
     */
    public void setModuleImgName(String moduleImgName) {
        this.moduleImgName = moduleImgName == null ? null : moduleImgName.trim();
    }
}